services:
  db_postgres:
    image: postgres:latest
    container_name: springboot_postgres
    environment:
      POSTGRES_DB: stackoverflow
      POSTGRES_USER: root
      POSTGRES_PASSWORD: is4tech
    ports:
      - "5432:5432"
    volumes:
      - stackoverflow_data:/var/lib/postgresql/data

volumes:
  stackoverflow_data:
    name: stackoverflow_data